name: cofipe
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  google_sign_in: ^6.2.1
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.10.0
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/icons/
